- name: WoW Packager
  uses: BigWigsMods/packager@v1.0.3

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ##CF_API_KEY: ${{ secrets.CF_API_KEY }}
      ##WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      ##WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Clone project
        uses: actions/checkout@v1

      - name: Package
        uses: BigWigsMods/packager@multitoc
